
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Say Hello
          command: echo "Hello, CircleCI!"
      - run:
          name: Output Date
          command: date

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
